spring:
  # MySQL 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/course_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234567
    hikari:
      maximum-pool-size: 10  # 连接池最大连接数
      connection-timeout: 30000
  jpa:
    hibernate:
          ddl-auto: validate  # prod环境仅校验表结构，不修改
          show-sql: false  # 关闭SQL日志
          properties:
          hibernate:
            format_sql: false
            dialect: org.hibernate.dialect.MySQL8Dialect  # MySQL8方言
          open-in-view: false